services:
  - type: web
    name: node-app
    env: node
    buildCommand: PUPPETEER_CACHE_DIR=/opt/render/project/src/.puppeteer_cache npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.puppeteer_cache
